// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinances.Domain.Model;

#nullable disable

namespace MyFinances.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329150356_EnlargeTickerTo20")]
    partial class EnlargeTickerTo20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyFinances.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currency_id");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("MyFinances.Domain.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDefault");

                    b.ToTable("currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "USD",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = true,
                            Name = "US Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EUR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Id = 3,
                            Code = "GBP",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "British Pound Sterling",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = 4,
                            Code = "JPY",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Japanese Yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 5,
                            Code = "CAD",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Canadian Dollar",
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AUD",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Australian Dollar",
                            Symbol = "A$"
                        },
                        new
                        {
                            Id = 7,
                            Code = "CHF",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Swiss Franc",
                            Symbol = "CHF"
                        },
                        new
                        {
                            Id = 8,
                            Code = "CNY",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Chinese Yuan",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 9,
                            Code = "ARS",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Argentine Peso",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 10,
                            Code = "BRL",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Brazilian Real",
                            Symbol = "R$"
                        },
                        new
                        {
                            Id = 11,
                            Code = "MXN",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Mexican Peso",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 12,
                            Code = "CLP",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Chilean Peso",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 13,
                            Code = "COP",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Colombian Peso",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 14,
                            Code = "PEN",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Peruvian Sol",
                            Symbol = "S/"
                        },
                        new
                        {
                            Id = 15,
                            Code = "UYU",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Uruguayan Peso",
                            Symbol = "$U"
                        },
                        new
                        {
                            Id = 16,
                            Code = "INR",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Indian Rupee",
                            Symbol = "₹"
                        },
                        new
                        {
                            Id = 17,
                            Code = "KRW",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "South Korean Won",
                            Symbol = "₩"
                        },
                        new
                        {
                            Id = 18,
                            Code = "SGD",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Singapore Dollar",
                            Symbol = "S$"
                        },
                        new
                        {
                            Id = 19,
                            Code = "HKD",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "Hong Kong Dollar",
                            Symbol = "HK$"
                        },
                        new
                        {
                            Id = 20,
                            Code = "NZD",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDefault = false,
                            Name = "New Zealand Dollar",
                            Symbol = "NZ$"
                        });
                });

            modelBuilder.Entity("MyFinances.Domain.CurrencyExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FromCurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("from_currency_id");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ToCurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("to_currency_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ToCurrencyId");

                    b.HasIndex("Date", "IsLatest");

                    b.HasIndex("FromCurrencyId", "ToCurrencyId", "IsLatest")
                        .IsUnique()
                        .HasFilter("IsLatest = 1");

                    b.ToTable("currency_exchange_rates");
                });

            modelBuilder.Entity("MyFinances.Domain.MarketData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<decimal>("Close")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("stocks_data");
                });

            modelBuilder.Entity("MyFinances.Domain.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("movements");
                });

            modelBuilder.Entity("MyFinances.Domain.Possession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("totalprice");

                    b.Property<decimal>("Worth")
                        .HasColumnType("decimal(12,5)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("possessions");
                });

            modelBuilder.Entity("MyFinances.Domain.Asset", b =>
                {
                    b.HasOne("MyFinances.Domain.Currency", "Currency")
                        .WithMany("Assets")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MyFinances.Domain.CurrencyExchangeRate", b =>
                {
                    b.HasOne("MyFinances.Domain.Currency", "FromCurrency")
                        .WithMany("FromExchangeRates")
                        .HasForeignKey("FromCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyFinances.Domain.Currency", "ToCurrency")
                        .WithMany("ToExchangeRates")
                        .HasForeignKey("ToCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("MyFinances.Domain.MarketData", b =>
                {
                    b.HasOne("MyFinances.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFinances.Domain.Currency", "Currency")
                        .WithMany("MarketData")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MyFinances.Domain.Movement", b =>
                {
                    b.HasOne("MyFinances.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFinances.Domain.Currency", "Currency")
                        .WithMany("Movements")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MyFinances.Domain.Possession", b =>
                {
                    b.HasOne("MyFinances.Domain.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFinances.Domain.Currency", "Currency")
                        .WithMany("Possessions")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MyFinances.Domain.Currency", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("FromExchangeRates");

                    b.Navigation("MarketData");

                    b.Navigation("Movements");

                    b.Navigation("Possessions");

                    b.Navigation("ToExchangeRates");
                });
#pragma warning restore 612, 618
        }
    }
}
